USE MASTER;
EXEC sp_who2

KILL 72
KILL 73

USE MASTER;
CREATE DATABASE database1


SELECT CONTATO_STATUS,COUNT(CONTATO_STATUS) 
FROM database1.dbo.CallsDia 
LEFT JOIN database3.dbo.Diario 
ON CallsDia.Nome=Diario.NOME 
WHERE CallsDia.DATA_ABERTURA_CONTATO>'2019-01-29' 
AND DATA_ABERTURA_CONTRATO IS NOT NULL 
GROUP BY CONTATO_STATUS
