USE MASTER;
EXEC sp_who2

KILL 72
KILL 73

USE MASTER;
CREATE DATABASE database1


SELECT VISITA_STATUS,COUNT(VISITA_STATUS) AS "Soma Consolidada" 
FROM database1.dbo.CallsDia 
LEFT JOIN database3.dbo.Diario 
ON CallsDia.Nome=Diario.NOME WHERE CallsDia.DATA_ABERTURA_SUPORTE>'2018-04-29' 
AND DATA_ABERTURA_VISITA IS NOT NULL AND VISITA_STATUS IS NOT NULL 
GROUP BY VISITA_STATUS ORDER BY "Soma Consolidada"
